name: CI Pipeline Test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # ──────────────────────────────────────────────────────────────
    - name: Checkout repo
      uses: actions/checkout@v4        # LFS not needed because we fabricate tiny CSVs

    # ──────────────────────────────────────────────────────────────
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # ──────────────────────────────────────────────────────────────
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # ──────────────────────────────────────────────────────────────
    - name: Create minimal test data (balanced classes)
      run: |
        mkdir -p clean results synthetic

        # 4 Pass, 4 Fail
        cat <<'EOF' > clean/oulad_master_engineered.csv
        code_module,code_presentation,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result,module_presentation_length,total_vle_clicks,has_vle_interaction,avg_assessment_score
        AAA,2013J,M,East Anglian Region,HE Qualification,10-20,35-55,0,60,N,Pass,268,100,1,85.5
        BBB,2013J,F,Scotland,HE Qualification,20-30,35-55,0,60,N,Fail,268, 50,1,78.2
        AAA,2013J,M,London Region,HE Qualification,20-30,35-55,1,60,N,Pass,268, 20,1,80.0
        BBB,2013J,F,Scotland,HE Qualification,10-20,35-55,1,60,N,Fail,268,150,1,70.4
        AAA,2013J,M,London Region,HE Qualification,20-30,35-55,0,60,N,Pass,268, 10,1,88.1
        AAA,2013J,F,London Region,HE Qualification,20-30,35-55,0,60,N,Pass,268, 70,1,82.3
        BBB,2013J,M,Scotland,HE Qualification,10-20,35-55,1,60,N,Fail,268, 40,1,65.0
        BBB,2013J,F,Scotland,HE Qualification,10-20,35-55,1,60,N,Fail,268,120,1,72.5
        EOF



        # Tiny synthetic mirrors
        cp clean/oulad_master_engineered.csv synthetic/synthetic_GaussianCopula.csv
        cp clean/oulad_master_engineered.csv synthetic/synthetic_CTGAN.csv

    # ──────────────────────────────────────────────────────────────
    - name: Run evaluation smoke-test
      run: python test_evaluation.py

    # ──────────────────────────────────────────────────────────────
    - name: Verify & print log
      run: |
        if [ -f results/test_evaluation.log ]; then
          echo "✅ Smoke test completed"; cat results/test_evaluation.log
        else
          echo "❌ Smoke test failed – log missing"; exit 1
        fi
